blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://pegasusheavy.github.io/bitbucket-cli/
    about: Check out our documentation for help and guides
  - name: Discussions
    url: https://github.com/pegasusheavy/bitbucket-cli/discussions
    about: Ask questions and discuss with the community
